token: "$LICHESS_BOT_TOKEN"

url: "https://lichess.org"

engine:
  dir: "./"
  name: "stoc"
  protocol: "uci"
  ponder: false
  uci_options:
    Hash: 16
    Threads: 1

challenge:
  accept_bot: true
  max_time: 1200
  min_time: 60
  inc: 10
  time_controls:
    - bullet
    - blitz
    - rapid
    - classical
  variants:
    - standard
  modes:
    - casual
    - rated
