token: "$LICHESS_BOT_TOKEN"

url: "https://lichess.org"

engine:
  dir: "./"
  name: "stoc"
  protocol: "uci"
  # This MUST be named uci_options so lichess-bot passes it to Stockfish
  uci_options:
    Hash: 16          # Limit memory cache to 16MB
    Threads: 1        # Use only 1 CPU thread

challenge:
  # Permite botului să accepte provocări automat
  accept_bot: true
  max_time: 1200
  min_time: 60
  inc: 10
  time_controls:
    - bullet
    - blitz
    - rapid
    - classical
  variants:
    - standard
  modes:
    - casual
    - rated
